#!/bin/bash

##############################################
#Checks if the results of the tests are okay #
##############################################

#Command line solver results
resultsNormalCL=( $(find . -regex ".*/results_[0-9]*_normal_command_line.txt" -type f) )
resultsBetaCL=( $(find . -regex ".*/results_[0-9]*_beta_command_line.txt" -type f) ) 
#XML solver results
resultsNormalXML=( $(find . -regex ".*/results_[0-9]*_normal_xml.txt" -type f) )
resultsBetaXML=( $(find . -regex ".*/results_[0-9]*_beta_xml.txt" -type f) ) 

#some checks on list's length
if [ ${#resultsNormalCL[@]} -ne ${#resultsNormalXML[@]} ]; then
  echo "[ERROR] Wrong results number in test case #1"
  exit 0
fi

if [ ${#resultsBetaCL[@]} -ne ${#resultsBetaXML[@]} ]; then
  echo "[ERROR] Wrong results number in test case #2"
  exit 0
fi

#Loop through files in order to check them pairwise
#Check normal distribution results
for ((i=0; i<${#resultsNormalCL[@]}; i++)); do
  diff ${resultsNormalCL[${i}]} ${resultsNormalXML[${i}]} >> check_diffs_normal.log
  echo "[OK] ${i} checked normal"
done
#Check beta distribution results
for ((i=0; i<${#resultsBetaCL[@]}; i++)); do
  diff ${resultsBetaCL[${i}]} ${resultsBetaXML[${i}]} >> check_diffs_beta.log
  echo "[OK] ${i} checked beta"
done
echo -e "\nCHECK COMPLETED!!\n"

#if log files are empty, no differences are found
if [ $(wc -c check_diffs_normal.log | cut -f 1 -d ' ') -eq 0 ]; then 
  echo -e "[OK] Normal distribution results are fine\n"
  rm check_diffs_normal.log
else 
  echo -e "[ERROR] Normal distribution results are different\n"
fi

if [ $(wc -c check_diffs_beta.log | cut -f 1 -d ' ') -eq 0 ]; then 
  echo -e "[OK] Beta distribution results are fine\n"
  rm check_diffs_beta.log
else 
  echo -e "[ERROR] Beta distribution results are different\n"
fi