#!/bin/bash

##############################################
#Checks if the results of the tests are okay #
##############################################

#Command line solver results
resultsNormalCL=$(find . -regex ".*/results_[0-9]*_normal_command_line.txt")
resultsBetaCL=$(find . -regex ".*/results_[0-9]*_beta_command_line.txt") 
#XML solver results
resultsNormalXML=$(find . -regex ".*/results_[0-9]*_normal_xml.txt")
resultsBetaXML=$(find . -regex ".*/results_[0-9]*_beta_xml.txt") 

#Loop through files in order to check them pairwise
#Check normal distribution results
i=0
while [ ${i} -lt ${#resultsNormalCL[@]} ]; do
  diff ${resultsNormalCL[${i}]} ${resultsNormalXML[${i}]} >> check_diffs_normal.log
  echo "${i} checked"
  i=$((i+1))
done 
#Check beta distribution results
i=0
while [ ${i} -lt ${#resultsBetaCL[@]} ]; do
  diff ${resultsBetaCL[${i}]} ${resultsBetaXML[${i}]} >> check_diffs_beta.log
  echo "${i} checked"
  i=$((i+1))
done 
echo -e "\nCHECK COMPLETED!!\n"