#!/bin/bash

#test PROSIT command line tool with many parameters

#Test Case 1:
#File:                test_case_1.txt
#Distribution:        Normal
#Average:             29338.9071 us
#Standard deviation:  3689.5235 us
#Prosit parameters:
#  Period (T):               100000 us
#  Reservation period (Ts):  25000 us
#  Budget (q):               [7500 - 10000] us, with an increment of 250 us 
T=100000
Ts=25000
step=100
increment=250
for i in {7500..10000..$increment}; do
  ../solver --cyclic \
            --budget $i \
            --task_period $T \
            --period $Ts \
            test_case_1.txt \
            z_2.txt \
            --verbose \
            --step $step \
            -M 4 &> results_$i_normal.txt
done

#Test Case 2:
#File:           test_case_2.txt
#Distribution:   Beta
#Alpha:          4.19843
#Beta:           24.6793
#Prosit parameters:
#  Period (T):               40000 us
#  Reservation period (Ts):  20000 us
#  Budget (q):               [7600 - 16000] us, with an increment of 200 us
T=40000
Ts=20000
step=100
increment=200
for i in {7500..10000..$increment}; do
  ../solver --cyclic \
            --budget $i \
            --task_period $T \
            --period $Ts \
            test_case_2.txt \
            z_2.txt \
            --verbose \
            --step $step \
            -M 4 &> results_$i_beta.txt
done